dist: trusty
sudo: required

language: c

addons:
  apt:
    packages:
    - gcc
    - gfortran
    - autotools-dev
    - libtool
    - gtk-doc-tools
    - gobject-introspection
    - gir1.2-glib-2.0
    - libgirepository1.0-dev
    - pkg-config
    - libglib2.0-dev
    - libgmp3-dev
    - libmpfr-dev
    - libgsl0-dev
    - libfftw3-dev
    - libcfitsio3-dev
    - libsundials-serial-dev
    - libnlopt-dev
    - texlive
    - texlive-bibtex-extra
    - texlive-science
    - tex4ht

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - NOCONFIGURE=yes ./autogen.sh

script: 
  - ./configure --enable-man --enable-gtk-doc
  - make V=1
  - make check

