os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

dist: trusty
sudo: required

language: c

addons:
  apt:
    packages:
    - gcc
    - gfortran
    - autotools-dev
    - libtool
    - gtk-doc-tools
    - gobject-introspection
    - gir1.2-glib-2.0
    - libgirepository1.0-dev
    - pkg-config
    - libglib2.0-dev
    - libgmp3-dev
    - libmpfr-dev
    - libgsl0-dev
    - libfftw3-dev
    - libcfitsio3-dev
    - libsundials-serial-dev
    - libnlopt-dev
    - texlive
    - texlive-bibtex-extra
    - texlive-science
    - texlive-publishers
    - tex4ht
    - perl
    - libxml-libxml-perl

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CONFDOCS="--enable-man --enable-gtk-doc" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CC="gcc-6"                               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then hash -r                                         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew tap homebrew/science                       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gcc                                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gobject-introspection              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gsl gtk-doc gmp mpfr               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install fftw cfitsio sundials              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install nlopt                              ; fi
  - NOCONFIGURE=yes ./autogen.sh

script: 
  - ./configure $CONFDOCS
  - make
  - make check
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make dist ; fi


