dist: trusty
sudo: required

os:
  - linux
  - osx

language: c

addons:
  apt:
    packages:
    - gcc
    - gfortran
    - autotools-dev
    - libtool
    - gtk-doc-tools
    - gobject-introspection
    - gir1.2-glib-2.0
    - libgirepository1.0-dev
    - pkg-config
    - libglib2.0-dev
    - libgmp3-dev
    - libmpfr-dev
    - libgsl0-dev
    - libfftw3-dev
    - libcfitsio3-dev
    - libsundials-serial-dev
    - libnlopt-dev
    - texlive
    - texlive-bibtex-extra
    - texlive-science
    - texlive-publishers
    - tex4ht
    - perl
    - libxml-libxml-perl

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - NOCONFIGURE=yes ./autogen.sh

script: 
  - ./configure --enable-man --enable-gtk-doc
  - make V=1
  - make check V=1
  - make dist V=1


