language: c

addons:
  apt:
    sources:
    - lucid
    packages:
    - gfortran
    - autotools-dev
    - libtool
    - gtk-doc-tools
    - gobject-introspection
    - gir1.2-glib-2.0
    - libgirepository1.0-dev
    - pkg-config
    - libglib2.0-dev
    - libgmp3-dev
    - libmpfr-dev
    - libgsl0-dev
    - libfftw3-dev

compiler:
  - clang
  - gcc

#  - sudo apt-get -qq update

before_install:
  - NOCONFIGURE=yes ./autogen.sh

